### ISSUE TITLE
Homework Submit

### ISSUE THREAD

**Issue by Hanyx2021** [Btlmd/sast2022-django-training#1]
https://git.tsinghua.edu.cn/hanyx21/django

**Comment by Btlmd** [comment]
Orz，俺先蹲一个部署 🐱

**Comment by Btlmd** [comment]
- 实现没问题
- 部署地址在我这里访问会出现
  ```
  Bad response. The server or forwarder response doesn't look like HTTP.
  ```
  不过我测试部署了一下是没问题的，大概是进程给关了 (?
- 如果加个 `.gitignore` 把 `migrations` 和 `__pycache__` 忽略就更加优雅了
