### ISSUE TITLE
Homework Submit

### ISSUE THREAD

**Issue by gearlessbu** [Btlmd/sast2022-django-training#12]
https://git.tsinghua.edu.cn/bjm21/django_train2022sast.git

部署：http://59.66.131.240:45394/

**Comment by Btlmd** [comment]
- 实现合理
- 可以把解析 JSON 的部分try一下，防止用户输入不是 JSON 导致 500
- `str(subs[0])+' '+str(subs[1])+' '+str(subs[2]))` 可作 `' '.join(map(str, subs))`。 看起来更加清晰简洁
