### ISSUE TITLE
Homework Submit

### ISSUE THREAD

**Issue by Azure-stars** [Btlmd/sast2022-django-training#13]
代码地址：https://github.com/Azure-stars/CS-summer2022/tree/main/Homework_Django/sast2022-django-training-master
部署地址：http://59.66.131.240:45409
使用nginx反向代理部署

**Comment by Btlmd** [comment]
部署地址 502 了 😢

**Comment by Btlmd** [comment]
- 实现没问题！
- `len(q) == False` 确实没问题，但总感觉有点怪怪的；这里即使是 len == 0，也可以使用 `.first()` 方法，此时会得到 None，再来判断 None。这种写法可能更简洁些
- `dic = json.loads(req.body)` 可以写到 `try` 中去，否则用户输入不是 JSON 时会 500 。
