### ISSUE TITLE
Homework Submit

### ISSUE THREAD

**Issue by IridescentPig** [Btlmd/sast2022-django-training#14]
https://github.com/IridescentPig/sast2022-django-training
部署：
http://59.66.131.240:45609

**Comment by Btlmd** [comment]
唔？部署 502了？

**Comment by Btlmd** [comment]
- 实现合理！

**Comment by IridescentPig** [comment]
> 唔？部署 502了？

之前忘记开后台运行了，现在应该可以访问了
