### ISSUE TITLE
迟来的submit

### ISSUE THREAD

**Issue by KujoStar** [Btlmd/sast2022-django-training#15]
代码仓库：https://github.com/KujoStar/sast2022-django-training
不知道部署好了没，可能还需要调试，三个新上传的代码文件应该没问题（本地调试没啥问题awa

**Comment by KujoStar** [comment]
部署地址：59.66.131.240:45401

**Comment by KujoStar** [comment]
哈人，好像这个地址不对，我的问题（

**Comment by Btlmd** [comment]
- 这个一个一个一个合理的实现啊！！！！
- vote 接口其实并不要求用户已经注册 Orz，所以按说样例前端给出的请求并不会含有 `user` 字段
- `views.py` 第 89 行似乎有一个逻辑错误，如果 `current_user` 不存在，后面创建的新用户并没有和新创建的 `Submission` 关联起来
- 直接保存 `subs` 数组的方式和我已经在 `utils.py` 中写好取用 `subs` 字段的方法不太兼容。具体来说，直接存数组会在 `subs` 字段中存储
  ```python
  '[1, 2, 3]'
  ```
  而在 `split` 后则变成了
  ```python
  ['[1,', '2,', '3]']
  ```
  从而可能在 `int` 函数调用时出现异常。
- Note：没有跑 mhgg 的代码，只是阅读了一遍，所以这些问题也未必真的存在，可能只是我没看懂 x

**Comment by KujoStar** [comment]
2022.8.1 update:
1. 修改了```views.py```中判断用户```current_user```是否存在的逻辑问题
2. 修改了```utils.py```中取用```subs```字段的方式（雾），如果直接保存```subs```的话应该改成```"subs": [int(x) for x in obj.subs]```就行（
3. 重新部署了代理，端口为59.66.131.240:45403，在postman测试是200 OK，在样例前端随意提交的时候会有错误码返回，这下应该部署完了Orz

**Comment by Btlmd** [comment]
涵涵 tql！！
