### ISSUE TITLE
HW submit

### ISSUE THREAD

**Issue by tjq21** [Btlmd/sast2022-django-training#17]
https://git.tsinghua.edu.cn/tjq21/2022sast-django-training

**Comment by Btlmd** [comment]
- 实现基本合理
- 有个小细节，当用户发来的请求不是 JSON 时，可能会导致 500，可以将解析 JSON 的语句用 `try` 包起来
- `utils.get_history` 看起来更像是 User 的方法，添加到 `models` 的 `User` 类中可能更优雅
- 这里
  ```python
  assert 'user' in req_dict.keys() and "没传进来用户名啊"
  ```
  在没有传入用户名时也会 500，因为 `assert` 引发的异常没有被捕获。此外，`assert` 的错误提示通常写法是
  ```python
  assert 'user' in req_dict.keys(), "没传进来用户名啊"
  ```
