### ISSUE TITLE
Homework Submit

### ISSUE THREAD

**Issue by zhaozkTHU** [Btlmd/sast2022-django-training#2]
[代码仓库](https://github.com/zhaozkTHU/sast2022-LeaderBoard)
部署地址: 59.66.131.240:46144

**Comment by Btlmd** [comment]
- 实现思路基本合理，但有些小地方
  - `urls.py` 中 `<slug:xxx>` 会将 xxx 作为 keyword argument 传入相应视图函数中，因此这里 slug 的名称必须和视图函数中一致。 
  - `submit` API 似乎没有遵守 API 接口约定，使用了 `name` 而不是 `user` 作为 JSON 中的属性。这种操作在前后端合作中较为令人窒息，可能导致前后端接不上。
  - `json.load` 使用不当。对于将字符串转换成 JSON，应该使用 `json.loads` 而不是 `json.load` ，`json.load` 传入的对象必须有 `read` 方法，比如文件。
  - 当用户输入不合法的时候，比如不是 JSON 或者 JSON 中缺乏相应属性时可能会 500，这里 try 一下可能会更好
  - 最好在调用 `utils.judge(info["content"])` 时将其结果直接保存下来，目前的写法在内容合法时会调用两次 `utils.judge` ，这样稍微有点耗资源（不过反正评测压力不大这么写也不是完全不行）
