### ISSUE TITLE
hw

### ISSUE THREAD

**Issue by Lethe10137** [Btlmd/sast2022-django-training#21]
https://github.com/Lethe10137/sast2022-django-training
59.66.131.240/45549

**Comment by Btlmd** [comment]
- 部署页面 404 了 (?
----------------
- 实现合理
- 在 `submit` 函数中即使 `replace` 后，仍然有可能解析失败，所以解析 JSON 时最好用 `try` 包起来 😃 
- Base64 的返回值非常严谨！强！

**Comment by Lethe10137** [comment]
我在2022-08-07 23:43:28进行了测试，59.66.131.240:45549似乎能和样例前端交互。


&nbsp;





&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: "Lambda ***@***.***&gt;; 
Date: 2022年8月7日(星期天) 晚上8:18
To: ***@***.***&gt;; 
Cc: "李骋昊  ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [Btlmd/sast2022-django-training] hw (Issue #21)





  
部署页面 404 了 (?
  
  
实现合理
 
在 submit 函数中即使 replace 后，仍然有可能解析失败，所以解析 JSON 时最好用 try 包起来 😃
 
Base64 的返回值非常严谨！强！
