### ISSUE TITLE
Homework submit

### ISSUE THREAD

**Issue by Sweetlemon68** [Btlmd/sast2022-django-training#3]
Git repository: [SAST2022-Django-training](https://git.tsinghua.edu.cn/mrj21/sast2022-django-training)

Backend deploying address (nginx + uwsgi): [http://59.66.131.240:45719/](http://59.66.131.240:45719)

EDIT: now http/https are both available at [http://sast.sweetlemon.top:45719/](http://sast.sweetlemon.top:45719), [https://sast.sweetlemon.top:45719/](https://sast.sweetlemon.top:45719).

**Comment by Btlmd** [comment]
- 实现合理
- HTTPS Orz ！
- Maybe set `DEBUG=False`
