### ISSUE TITLE
Homework submit

### ISSUE THREAD

**Issue by YfLi03** [Btlmd/sast2022-django-training#4]
https://github.com/YfLi03/SASTSummer_django
deploy: http://sast.iceeera.com:45758
using uwsgi

**Comment by YfLi03** [comment]
*突然想到一个可能存在的问题
result.txt中的换行需要是\n而不是\r\n

**Comment by Btlmd** [comment]
- 实现合理！
- 处理用户输入时可以再增加个 `try`，防止用户输入不是 JSON 时 500
- `utils.get_history` 设置成模型的方法可能比放到 utils 里更合理
- 膜猫猫是标配了 (?
- `DEBUG=True` 好评

**Comment by yhx-12243** [comment]
谔谔，所有名为 “jkjkmxmx | 涵涵tql” 的提交全都是我交的 :doge:

**Comment by Btlmd** [comment]
> 谔谔，所有名为 “jkjkmxmx | 涵涵tql” 的提交全都是我交的 :doge:

hhhhhhhhhh，原来是这样 😹

**Comment by YfLi03** [comment]
> * 实现合理！
> * 处理用户输入时可以再增加个 `try`，防止用户输入不是 JSON 时 500
> * `utils.get_history` 设置成模型的方法可能比放到 utils 里更合理
> * 膜猫猫是标配了 (?
> * `DEBUG=True` 好评

应该是DEBUG = False吧（

**Comment by Btlmd** [comment]
> > * 实现合理！
> > * 处理用户输入时可以再增加个 `try`，防止用户输入不是 JSON 时 500
> > * `utils.get_history` 设置成模型的方法可能比放到 utils 里更合理
> > * 膜猫猫是标配了 (?
> > * `DEBUG=True` 好评
> 
> 应该是DEBUG = False吧（

确实，是 `DEBUG=False` 好评 😹
