### ISSUE TITLE
homework submit

### ISSUE THREAD

**Issue by whimmmmm** [Btlmd/sast2022-django-training#5]
https://git.tsinghua.edu.cn/luoyq21/django_hw.git

http://59.66.131.240:45298/

**Comment by Btlmd** [comment]
- 部署链接似乎已经失效 (?
- 实现思路基本合理，但也存在一些问题
  - `/history` 的返回内容不符合 API 规范，没有返回一整个 JSON，而是一些 JSON 字符串的拼接
    - 这大概是因为你 `views.py` 的 41 行使用了 `HttpRespose` 而不是 `JsonResponse` 
  - 用户输入不是 JSON 时会直接因为解析失败而 500，这里可以考虑 try 捕获一下
  - 部署时考虑 `DEBUG=False` 
- 代码风格
  ```python
  if 'User-Agent' not in req.headers \
      or 'requests' in req.headers['User-Agent']:
      return JsonResponse({
        "code": -1
      })
   else:
      ...
  ```
    `return` 后的 else 看起来怪怪的，也大概没有必要 (?
