### ISSUE TITLE
homework submit

### ISSUE THREAD

**Issue by Xial-kotori** [Btlmd/sast2022-django-training#6]
Git repository: [Lycoris Recoil](https://git.tsinghua.edu.cn/yuancf21/summer2022-hw4-django)

Blank (uWSGI + Nginx): http://59.66.131.240:45214

**Comment by Btlmd** [comment]
- 实现合理
- 用户输入不是 JSON 时会 500， 可以考虑给这里加个 `try` 
- `DEBUG=True` 好评
- `numpy` 好评
- （坏了，你的作业也被猫猫污染了qwq
