### ISSUE TITLE
Homework Submit

### ISSUE THREAD

**Issue by tongyx361** [Btlmd/sast2022-django-training#7]
部署地址：暂无（装不上uwsgi，回头再试试...）
代码地址：https://github.com/KiDrain61/LeaderBoard
姓名：童雨轩

**Comment by Btlmd** [comment]
- 实现合理
- `/submit`，用户输入不符合 JSON 格式时会 500，可以使用 try 捕获一下 
- 直接将 `e` 放入 JsonResponse 中可能会导致不能正确序列化而报错
- `numpy` 好评~！
