### ISSUE TITLE
Homework submit

### ISSUE THREAD

**Issue by srzer** [Btlmd/sast2022-django-training#8]
https://git.tsinghua.edu.cn/srz21/django-training

**Comment by srzer** [comment]
部署端口：暂无，别急

**Comment by srzer** [comment]
部署端口：http://59.66.131.240:45874

**Comment by Btlmd** [comment]
Hoops，部署地址 404 了 ❗

**Comment by Btlmd** [comment]
- 实现思路没问题
- `urls.py` 中使用 `int` 匹配用户名可能导致创建了非纯数字的用户名没法被匹配到（虽然说用户名的含义其实我们希望它是个学号
- 代码风格
  - 通常使用 `is None` 来判断变量是否是 `None` 而不是 `== None` ，避免 `__eq__` 函数的定义使得语句出现意料之外的结果（虽然在这里其实没问题
  - 这里
    ```python
      sub = ""
      for i in range(len(score[1])):
        sub = sub + str(score[1][i]) + " "
    ```
    用
    ```python
    sub = ' '.join(map(str, score[1]))
    ```
    可能更好
